appName: crossplane
repoUrl: https://charts.crossplane.io/stable
chartVersion: "1.19.0"
namespace: crossplane-system
customValues:
  args:
    - "--debug"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"