---
# Source: flux-template/templates/helm-release.yaml
# This is a HelmRelease CRD that Flux will use to deploy crossplane.
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 1h
  chart:
    spec:
      chart: crossplane
      version: "1.19.0"
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
  releaseName: crossplane
  targetNamespace: crossplane-system
  install:
    createNamespace: true
  # Optional customizations
  values:
    args:
      - "--debug"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
