---
# This is a HelmRelease CRD that Flux will use to deploy {{ .Values.appName }}.
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  interval: {{ .Values.interval }}
  chart:
    spec:
      chart: {{ .Values.appName }}
      version: {{ quote .Values.chartVersion }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.appName }}
        namespace: flux-system
  releaseName: {{ .Values.appName }}
  targetNamespace: {{ .Values.namespace }}
  install:
    createNamespace: true
  {{- if .Values.customValues }}
  # Optional customizations
  values:
    {{- range $key, $value := .Values.customValues }}
    {{ $key }}:
      {{- if kindIs "slice" $value }}
      {{- range $item := $value }}
      - {{ quote $item }}
      {{- end }}
      {{- else }}
      {{- toYaml $value | trim | nindent 6 }}
      {{- end }}
    {{- end }}
  {{- end }}